<?php
ini_set('display_errors', 1); 

$username="root";
$password="30mcrt983";
$database="gpb";
$prefix="jgpb_";

function total($table) {
    global $username, $password, $database;
    mysql_connect("localhost", $username, $password);
    mysql_select_db($database) or die( "Unable to select database");
    
    $record = mysql_query("SELECT * FROM $table;");
    if ($record) {
       $tot = mysql_numrows($record);  
       echo '<tr><td>'.$table.'</td><td><b>'.$tot.'</b></td></tr>';
       }
    else {
       echo '<tr><td>'.$table.'</td><td>0</td></tr>';
    }
}
?>
<table>
<?php
total($prefix."assets");
total($prefix."associations");
total($prefix."banners");
total($prefix."banner_clients");
total($prefix."banner_tracks");
total($prefix."categories");
total($prefix."cf_customfields");
total($prefix."cf_filtertypes");
total($prefix."contact_details");
total($prefix."content");
total($prefix."content_frontpage");
total($prefix."content_rating");
total($prefix."core_log_searches");
total($prefix."extensions");
total($prefix."finder_filters");
total($prefix."finder_links");
total($prefix."finder_links_terms0");
total($prefix."finder_links_terms1");
total($prefix."finder_links_terms2");
total($prefix."finder_links_terms3");
total($prefix."finder_links_terms4");
total($prefix."finder_links_terms5");
total($prefix."finder_links_terms6");
total($prefix."finder_links_terms7");
total($prefix."finder_links_terms8");
total($prefix."finder_links_terms9");
total($prefix."finder_links_termsa");
total($prefix."finder_links_termsb");
total($prefix."finder_links_termsc");
total($prefix."finder_links_termsd");
total($prefix."finder_links_termse");
total($prefix."finder_links_termsf");
total($prefix."finder_taxonomy");
total($prefix."finder_taxonomy_map");
total($prefix."finder_terms");
total($prefix."finder_terms_common");
total($prefix."finder_tokens");
total($prefix."finder_tokens_aggregate");
total($prefix."finder_types");
total($prefix."jf_content");
total($prefix."jf_languages");
total($prefix."jf_languages_ext");
total($prefix."jf_tableinfo");
total($prefix."languages");
total($prefix."menu");
total($prefix."menu_types");
total($prefix."messages");
total($prefix."messages_cfg");
total($prefix."modules");
total($prefix."modules_menu");
total($prefix."newsfeeds");
total($prefix."overrider");
total($prefix."phocadownload");
total($prefix."phocadownload_categories");
total($prefix."phocadownload_file_votes");
total($prefix."phocadownload_file_votes_statistics");
total($prefix."phocadownload_layout");
total($prefix."phocadownload_licenses");
total($prefix."phocadownload_tags");
total($prefix."phocadownload_tags_ref");
total($prefix."phocadownload_user_stat");
total($prefix."redirect_links");
total($prefix."schemas");
total($prefix."session");
total($prefix."template_styles");
total($prefix."updates");
total($prefix."update_categories");
total($prefix."update_sites");
total($prefix."update_sites_extensions");
total($prefix."usergroups");
total($prefix."users");
total($prefix."user_notes");
total($prefix."user_profiles");
total($prefix."user_usergroup_map");
total($prefix."viewlevels");
total($prefix."virtuemart_adminmenuentries");
total($prefix."virtuemart_calcs");
total($prefix."virtuemart_calc_categories");
total($prefix."virtuemart_calc_countries");
total($prefix."virtuemart_calc_shoppergroups");
total($prefix."virtuemart_calc_states");
total($prefix."virtuemart_categories");
total($prefix."virtuemart_categories_en_gb");
total($prefix."virtuemart_categories_it_it");
total($prefix."virtuemart_category_categories");
total($prefix."virtuemart_category_medias");
total($prefix."virtuemart_configs");
total($prefix."virtuemart_countries");
total($prefix."virtuemart_coupons");
total($prefix."virtuemart_currencies");
total($prefix."virtuemart_customs");
total($prefix."virtuemart_invoices");
total($prefix."virtuemart_manufacturercategories");
total($prefix."virtuemart_manufacturercategories_en_gb");
total($prefix."virtuemart_manufacturercategories_it_it");
total($prefix."virtuemart_manufacturers");
total($prefix."virtuemart_manufacturers_en_gb");
total($prefix."virtuemart_manufacturers_it_it");
total($prefix."virtuemart_manufacturer_medias");
total($prefix."virtuemart_medias");
total($prefix."virtuemart_migration_oldtonew_ids");
total($prefix."virtuemart_modules");
total($prefix."virtuemart_orders");
total($prefix."virtuemart_orderstates");
total($prefix."virtuemart_order_calc_rules");
total($prefix."virtuemart_order_histories");
total($prefix."virtuemart_order_items");
total($prefix."virtuemart_order_userinfos");
total($prefix."virtuemart_paymentmethods");
total($prefix."virtuemart_paymentmethods_en_gb");
total($prefix."virtuemart_paymentmethods_it_it");
total($prefix."virtuemart_paymentmethod_shoppergroups");
total($prefix."virtuemart_permgroups");
total($prefix."virtuemart_products");
total($prefix."virtuemart_products_en_gb");
total($prefix."virtuemart_products_it_it");
total($prefix."virtuemart_product_categories");
total($prefix."virtuemart_product_customfields");
total($prefix."virtuemart_product_manufacturers");
total($prefix."virtuemart_product_medias");
total($prefix."virtuemart_product_prices");
total($prefix."virtuemart_product_relations");
total($prefix."virtuemart_product_shoppergroups");
total($prefix."virtuemart_ratings");
total($prefix."virtuemart_rating_reviews");
total($prefix."virtuemart_rating_votes");
total($prefix."virtuemart_shipmentmethods");
total($prefix."virtuemart_shipmentmethods_en_gb");
total($prefix."virtuemart_shipmentmethods_it_it");
total($prefix."virtuemart_shipmentmethod_shoppergroups");
total($prefix."virtuemart_shoppergroups");
total($prefix."virtuemart_states");
total($prefix."virtuemart_userfields");
total($prefix."virtuemart_userfield_values");
total($prefix."virtuemart_userinfos");
total($prefix."virtuemart_vendors");
total($prefix."virtuemart_vendors_en_gb");
total($prefix."virtuemart_vendors_it_it");
total($prefix."virtuemart_vendor_medias");
total($prefix."virtuemart_vmusers");
total($prefix."virtuemart_vmuser_shoppergroups");
total($prefix."virtuemart_waitingusers");
total($prefix."virtuemart_worldzones");
total($prefix."weblinks");
?>    
</table>
<?php

